-- Populate who_imci_chunks table with WHO IMCI and IAP pediatric guidelines
-- Embeddings start as placeholders and will be regenerated by Python script using Gemini API

-- Clear existing data (optional - comment out if you want to keep it)
-- DELETE FROM who_imci_chunks;

-- WHO IMCI - Fever Management
INSERT INTO who_imci_chunks (content, source, source_url, chapter, embedding) VALUES
(
  'Fever is a common presenting complaint in children and infants. Red Flags for Serious Illness: Pale, mottled, ashen or blue skin, lips or tongue; Limp, weak, or unresponsive; Difficulty breathing; Stridor in calm child; Severe malnutrition; Bulging fontanelle; Stiff neck; Petechial rash; Jaundice in first 24 hours. Assess general danger signs in all febrile children.',
  'WHO_IMCI_FEVER_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Danger Signs and Assessment',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Management of Fever without Focus in Office Practice: Take accurate history of fever duration, pattern, and associated symptoms. Perform physical examination including vital signs, general appearance, and specific system examination. Check for danger signs including abnormal respiratory rate, severe malnutrition, dehydration, or altered consciousness. If any danger sign present, refer urgently to hospital. Classify as severe pneumonia if respiratory rate elevated with general danger sign.',
  'WHO_IMCI_FEVER_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Fever Management Protocol',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Severe Pneumonia in Infants (<2 months): General danger signs OR Stridor in calm child OR Severe malnutrition. Very severe pneumonia: General danger signs. Fast breathing alone = non-severe pneumonia. Key vital sign: Count respiratory rate for full minute. For infants <2 months, RR ≥60 is fast breathing. For 2-59 months, RR ≥50 is fast breathing.',
  'WHO_IMCI_FEVER_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Pneumonia Classification',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Hospital Referral Criteria for Fever: Refer to hospital if: General danger sign present; Severe pneumonia; Very severe pneumonia; Complicated malaria; Severe dehydration; Meningitis suspected; Severe malnutrition with complications; Measles with complications; Severe diarrhea with blood or dehydration; Severe anemia; Inability to drink or breastfeed; Persistent vomiting; Lethargy or unconsciousness.',
  'WHO_IMCI_FEVER_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Hospital Referral Criteria',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- WHO IMCI - Pneumonia Assessment
(
  'Pneumonia Assessment Protocol: Ask about: Cough or difficult breathing for how many days; Anywhere difficult to breathe (lower chest indrawing); Stridor when calm; Difficulty drinking or breastfeeding; Lethargy or unconsciousness; Look: Check for any general danger sign; Stridor in calm child; Lower chest wall indrawing; Nasal flaring. Count respiratory rate for full minute in a calm child.',
  'WHO_IMCI_PNEUMONIA_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Pneumonia Assessment Steps',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Fast Breathing (Non-severe Pneumonia) in Infants: Age <2 months with fast breathing only (no chest indrawing, no stridor, no danger signs). Age 2-59 months with fast breathing only (RR 40-49, no chest indrawing, no stridor, no danger signs). Treat with first-line antibiotic: Amoxicillin 15-20mg/kg twice daily for 5 days. Advise caregiver on general care, signs of severe illness, and follow-up in 2 days.',
  'WHO_IMCI_PNEUMONIA_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Non-Severe Pneumonia Treatment',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Severe Pneumonia Management: Lower chest wall indrawing OR Stridor in calm child OR General danger sign. Hospitalize immediately. Treatment: Injectable antibiotics (Ceftriaxone 50-80mg/kg/day in 2 divided doses or Ampicillin + Gentamicin). Oxygen if SpO2 <90%. Ensure adequate hydration. Monitor closely for complications.',
  'WHO_IMCI_PNEUMONIA_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Severe Pneumonia Management',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- WHO IMCI - General Danger Signs
(
  'Classification of General Danger Signs in Children: Inability to drink or breastfeed; Persistent vomiting; Convulsions or loss of consciousness; Lethargy or unconsciousness; Stridor in calm child; Severe malnutrition (visible severe wasting or bipedal edema); Jaundice; Pallor (severe anemia); Any sign of dehydration with more than 2 signs: lethargy/unconsciousness, sunken eyes, unable to drink, skin pinch goes back very slowly (>2 seconds).',
  'WHO_IMCI_GENERAL_DANGER_SIGNS',
  'https://www.who.int/publications/i/item/9789241514668',
  'General Danger Signs Classification',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Management of Child with General Danger Sign: If any general danger sign present, refer urgently to hospital for skilled care. Do not delay. Provide first aid before referral if applicable. Refer the child in appropriate condition (avoid hypothermia, maintain airway, position recovery if unconscious). Ensure supervised transport with caregiver. Do not send unattended.',
  'WHO_IMCI_GENERAL_DANGER_SIGNS',
  'https://www.who.int/publications/i/item/9789241514668',
  'General Danger Sign Management',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- WHO IMCI - Diarrhea Assessment
(
  'Diarrhea Classification: Assess for: Diarrhea (<3 stools per day is not diarrhea); Blood in stool; Signs of dehydration (lethargy/unconsciousness, sunken eyes, unable to drink, skin pinch goes back very slowly). Very severe dehydration: Lethargy or unconsciousness AND inability to drink. Severe dehydration: Two or more signs (sunken eyes, drinks eagerly, skin pinch goes back slowly). Some dehydration: Only one sign of dehydration.',
  'WHO_IMCI_DIARRHEA_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Diarrhea Classification and Dehydration',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Diarrhea with Blood (Dysentery): Refer urgently to hospital if severe dehydration, lethargy, or unable to drink. If non-severe: Treat with ORS and zinc supplementation. Give ORS 50-100ml/kg over 4 hours or until hydration restored. Reassess hydration every 1-2 hours. Maintenance: 10ml/kg for each stool. Zinc: 10mg/day (or 20mg if >6 months) for 10-14 days.',
  'WHO_IMCI_DIARRHEA_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Dysentery Treatment Protocol',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- IAP Fever Guidelines
(
  'IAP Guidelines - Management of Fever in Children: Fever is most common presenting complaint in pediatric practice. Assessment should include: Onset, duration, pattern (continuous/intermittent), associated symptoms, previous fever episodes. Vital signs: Temperature (method - axillary/rectal), heart rate, respiratory rate, blood pressure. Physical examination: General appearance, skin turgor, capillary refill time, mucous membranes.',
  'IAP_FEVER_GUIDELINES_PEDIATRIC',
  'https://www.iapindia.org/guidelines',
  'Fever Assessment Protocol',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'IAP - Danger Signs Requiring Hospitalization: Lethargy or difficult to arouse; Altered mental status or confusion; Respiratory distress or tachypnea; Hypotension or shock (poor perfusion); Severe dehydration; Rash with fever; Neck stiffness or altered consciousness; Seizures; Inability to tolerate oral intake; Cyanosis or SpO2 <94%.',
  'IAP_FEVER_GUIDELINES_PEDIATRIC',
  'https://www.iapindia.org/guidelines',
  'IAP Hospitalization Criteria',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- IAP Malnutrition
(
  'IAP Classification of Protein-Energy Malnutrition: Normal: Weight/Age >80% of expected; Grade I: 71-80%; Grade II: 61-70%; Grade III: 51-60%; Grade IV: ≤50%. Severe Acute Malnutrition (SAM): MUAC <11.5cm (1-5 years) or weight-for-height <70% and/or edema. Stunting: Height-for-age <95%. Wasting: Weight-for-height <85%.',
  'IAP_MALNUTRITION_GUIDELINES',
  'https://www.iapindia.org/guidelines',
  'Malnutrition Classification',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Management of Severely Malnourished Child: Assess for complications (edema, hepatomegaly, infections, micronutrient deficiencies). Refer to hospital if: Severe acute malnutrition with complications, concurrent infections requiring hospitalization, inability to tolerate oral intake, medical complications. Provide therapeutic nutrition. Start micronutrient supplementation (Vitamin A, zinc, iron, folic acid). Monitor anthropometric indices.',
  'IAP_MALNUTRITION_GUIDELINES',
  'https://www.iapindia.org/guidelines',
  'SAM Management Protocol',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- Vital Signs and Respiratory Assessment
(
  'Normal Vital Signs in Children: Neonate (0-3 months): HR 120-160, RR 40-60; Infant (3-12 months): HR 100-160, RR 30-40; Toddler (1-3 years): HR 90-150, RR 24-40; Preschool (3-6 years): HR 70-110, RR 22-34; School age (6+ years): HR 70-100, RR 18-30. Temperature: Normal 36.5-37.5°C (axillary). Tachypnea defined as RR exceeding age-specific norms.',
  'WHO_IMCI_VITAL_SIGNS',
  'https://www.who.int/publications/i/item/9789241514668',
  'Vital Signs Reference Ranges',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Respiratory Rate Assessment in Pneumonia: Count for full minute in calm child. Fast breathing thresholds: <2 months: ≥60/min; 2-59 months: ≥50/min; 5+ years: ≥40/min. Document respiratory pattern: labored vs quiet, use of accessory muscles, nasal flaring, grunting. Assess for chest wall indrawing (lower chest indrawing indicates severe pneumonia). Stridor (high-pitched breathing) indicates airway obstruction.',
  'WHO_IMCI_RESPIRATORY_ASSESSMENT',
  'https://www.who.int/publications/i/item/9789241514668',
  'Respiratory Rate and Pattern Assessment',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- Severe Acute Malnutrition (SAM)
(
  'Severe Acute Malnutrition (SAM) - Diagnostic Criteria: Child must have ONE of the following: Weight-for-height <70% of median; MUAC <11.5cm (12-59 months); Bilateral pitting edema (nutritional edema). Risk of mortality increased significantly in SAM. Associated complications: Immunosuppression, increased infection risk, electrolyte abnormalities, hypoglycemia, hypothermia, impaired wound healing.',
  'WHO_IMCI_SAM_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'SAM Diagnostic Criteria',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'SAM Management Phases: Phase 1 (Stabilization): Address infections, metabolic complications, fluid/electrolyte imbalance. Monitor closely for refeeding syndrome. Phase 2 (Rehabilitation): Gradual nutritional rehabilitation with therapeutic feeds. Phase 3 (Follow-up): Continued nutrition support and growth monitoring. Refer SAM with complications to tertiary center. Key: Treat infections, correct micronutrient deficiencies, ensure gradual refeeding.',
  'WHO_IMCI_SAM_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'SAM Management Phases',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- Neonatal Assessment
(
  'Assessment of Neonatal Danger Signs: Age <7 days: Inability to drink, convulsions, lethargy/unconsciousness, stridor, severe respiratory distress, omphalitis (umbilical cord infection), skin pustules, skin cord alone with blood, fever (axillary temperature ≥37.5°C), hypothermia (<36.5°C), jaundice visible on palms/soles on day 1-2 or on body day 3+. Yellow soles on day 1 = urgent referral.',
  'WHO_IMCI_NEONATAL_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Neonatal Danger Signs',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'Sepsis Risk Assessment in Neonates: Risk factors: Maternal fever/infection during labor, prolonged rupture of membranes >18 hours, foul-smelling amniotic fluid, preterm delivery, low birth weight. Signs: Fever or hypothermia, inability to feed, lethargy, excessive crying/irritability, convulsions, jaundice, skin pustules, umbilical cord inflammation, bleeding, loose stools. Refer all suspected neonatal sepsis urgently to hospital for blood culture and antibiotics.',
  'WHO_IMCI_NEONATAL_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Neonatal Sepsis Assessment',
  array_fill(0.0::float8, ARRAY[768])::vector
),

-- Low Birth Weight Assessment
(
  'Low Birth Weight (LBW) Definition: Birth weight <2500g regardless of gestational age. Categories: Moderate LBW 1500-2499g, Very LBW 1000-1499g, Extremely LBW <1000g. LBW infants at higher risk for: Hypothermia, hypoglycemia, infection, feeding difficulties, respiratory distress, jaundice. Kangaroo care beneficial: Skin-to-skin contact for thermal regulation. Exclusive breastfeeding recommended when possible.',
  'WHO_IMCI_LBW_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'Low Birth Weight Classification',
  array_fill(0.0::float8, ARRAY[768])::vector
),
(
  'LBW Management and Follow-up: Monitor for signs of sepsis, hypothermia, hypoglycemia. Frequent feeding (8-12 times/day). Vitamin A supplementation per age. Ensure complete immunization including BCG, Hepatitis B. Close follow-up for growth monitoring. Use WHO growth charts for LBW. Developmental screening. Assess for complications (retinopathy of prematurity, chronic lung disease, neurological sequelae).',
  'WHO_IMCI_LBW_GUIDELINES',
  'https://www.who.int/publications/i/item/9789241514668',
  'LBW Management Protocol',
  array_fill(0.0::float8, ARRAY[768])::vector
);

-- Verify insertion
SELECT COUNT(*) as total_chunks, COUNT(DISTINCT source) as unique_sources FROM who_imci_chunks;
SELECT source, COUNT(*) as chunk_count FROM who_imci_chunks GROUP BY source ORDER BY source;
