import 'dart:async';

import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/care_log_summary.dart';
import '../models/log_entry.dart';

/// Service for CRUD operations on the `care_logs` Supabase table.
///
/// Modular design — supports today's logs now, and can easily extend
/// to 7-day trends, 30-day analysis, or per-type aggregations later.
class CareLogService {
  CareLogService._();
  static final CareLogService instance = CareLogService._();

  SupabaseClient get _db => Supabase.instance.client;
  static const _table = 'care_logs';

  String _resolveBabyId(String? babyId) {
    final resolved =
        babyId ?? _db.auth.currentSession?.user.id ?? _db.auth.currentUser?.id;
    if (resolved == null || resolved.isEmpty) {
      throw StateError('No authenticated user. Unable to resolve baby_id.');
    }
    return resolved;
  }

  // ── INSERT ──────────────────────────────────────────────────────────────

  /// Insert a new care log entry. Returns the created LogEntry.
  Future<LogEntry> addLog({
    required LogType type,
    required Map<String, dynamic> value,
    String? babyId,
  }) async {
    final resolvedBabyId = _resolveBabyId(babyId);

    final entry = LogEntry(
      id: '', // auto-generated by Supabase
      babyId: resolvedBabyId,
      timestamp: DateTime.now(),
      type: type,
      data: value,
    );

    try {
      final response = await _db
          .from(_table)
          .insert(entry.toInsertJson())
          .select()
          .single()
          .timeout(const Duration(seconds: 6));

      return LogEntry.fromJson(response);
    } on PostgrestException catch (e) {
      throw Exception(
        'Failed to insert care log for baby_id=$resolvedBabyId: ${e.message}',
      );
    }
  }

  // ── FETCH TODAY'S LOGS ──────────────────────────────────────────────────

  /// Fetch all logs from today (local time), ordered newest first.
  Future<List<LogEntry>> fetchTodayLogs({String? babyId}) async {
    final resolvedBabyId = _resolveBabyId(babyId);
    final now = DateTime.now();
    final startOfDay = DateTime(now.year, now.month, now.day);

    final response = await _db
        .from(_table)
        .select()
        .eq('baby_id', resolvedBabyId)
        .gte('created_at', startOfDay.toUtc().toIso8601String())
        .order('created_at', ascending: false)
        .timeout(const Duration(seconds: 6));

    return (response as List)
        .map((row) => LogEntry.fromJson(row as Map<String, dynamic>))
        .toList();
  }

  /// Fetch today's logs filtered by type.
  Future<List<LogEntry>> fetchTodayLogsByType({
    required LogType type,
    String? babyId,
  }) async {
    final resolvedBabyId = _resolveBabyId(babyId);
    final now = DateTime.now();
    final startOfDay = DateTime(now.year, now.month, now.day);

    final response = await _db
        .from(_table)
        .select()
        .eq('baby_id', resolvedBabyId)
        .eq(
          'type',
          type == LogType.diaper
              ? 'diaper'
              : type == LogType.feeding
              ? 'feeding'
              : 'symptom',
        )
        .gte('created_at', startOfDay.toUtc().toIso8601String())
        .order('created_at', ascending: false)
        .timeout(const Duration(seconds: 6));

    return (response as List)
        .map((row) => LogEntry.fromJson(row as Map<String, dynamic>))
        .toList();
  }

  // ── FETCH BY DATE RANGE (for trends) ────────────────────────────────────

  /// Fetch logs within a date range. Use for 7-day/30-day trends.
  Future<List<LogEntry>> fetchLogsByDateRange({
    required DateTime from,
    required DateTime to,
    String? babyId,
    LogType? type,
  }) async {
    final resolvedBabyId = _resolveBabyId(babyId);

    var query = _db
        .from(_table)
        .select()
        .eq('baby_id', resolvedBabyId)
        .gte('created_at', from.toUtc().toIso8601String())
        .lte('created_at', to.toUtc().toIso8601String());

    if (type != null) {
      query = query.eq(
        'type',
        type == LogType.diaper
            ? 'diaper'
            : type == LogType.feeding
            ? 'feeding'
            : 'symptom',
      );
    }

    final response = await query
        .order('created_at', ascending: false)
        .timeout(const Duration(seconds: 6));

    return (response as List)
        .map((row) => LogEntry.fromJson(row as Map<String, dynamic>))
        .toList();
  }

  // ── BUILD SUMMARY FOR EVALUATOR ──────────────────────────────────────

  /// Fetch today's logs and aggregate them into a [CareLogSummary]
  /// for the neonatal health evaluation engine.
  ///
  /// Returns [CareLogSummary.empty()] on failure so the evaluator
  /// can gracefully fall back to vitals-only scoring.
  Future<CareLogSummary> buildTodaySummary({String? babyId}) async {
    try {
      final logs = await fetchTodayLogs(babyId: babyId);
      return CareLogSummary.fromLogs(logs);
    } catch (_) {
      return const CareLogSummary.empty();
    }
  }

  // ── DELETE ──────────────────────────────────────────────────────────────

  /// Delete a log entry by ID.
  Future<void> deleteLog(String id) async {
    await _db.from(_table).delete().eq('id', id);
  }
}
