import 'package:supabase_flutter/supabase_flutter.dart';

import '../models/log_entry.dart';

/// Service for CRUD operations on the `care_logs` Supabase table.
///
/// Modular design — supports today's logs now, and can easily extend
/// to 7-day trends, 30-day analysis, or per-type aggregations later.
class CareLogService {
  CareLogService._();
  static final CareLogService instance = CareLogService._();

  SupabaseClient get _db => Supabase.instance.client;
  static const _table = 'care_logs';

  // ── INSERT ──────────────────────────────────────────────────────────────

  /// Insert a new care log entry. Returns the created LogEntry.
  Future<LogEntry> addLog({
    required LogType type,
    required Map<String, dynamic> value,
    String babyId = 'default',
  }) async {
    final entry = LogEntry(
      id: '', // auto-generated by Supabase
      babyId: babyId,
      timestamp: DateTime.now(),
      type: type,
      data: value,
    );

    final response = await _db
        .from(_table)
        .insert(entry.toInsertJson())
        .select()
        .single();

    return LogEntry.fromJson(response);
  }

  // ── FETCH TODAY'S LOGS ──────────────────────────────────────────────────

  /// Fetch all logs from today (local time), ordered newest first.
  Future<List<LogEntry>> fetchTodayLogs({String babyId = 'default'}) async {
    final now = DateTime.now();
    final startOfDay = DateTime(now.year, now.month, now.day);

    final response = await _db
        .from(_table)
        .select()
        .eq('baby_id', babyId)
        .gte('created_at', startOfDay.toUtc().toIso8601String())
        .order('created_at', ascending: false);

    return (response as List)
        .map((row) => LogEntry.fromJson(row as Map<String, dynamic>))
        .toList();
  }

  /// Fetch today's logs filtered by type.
  Future<List<LogEntry>> fetchTodayLogsByType({
    required LogType type,
    String babyId = 'default',
  }) async {
    final now = DateTime.now();
    final startOfDay = DateTime(now.year, now.month, now.day);

    final response = await _db
        .from(_table)
        .select()
        .eq('baby_id', babyId)
        .eq('type', type == LogType.diaper
            ? 'diaper'
            : type == LogType.feeding
                ? 'feeding'
                : 'symptom')
        .gte('created_at', startOfDay.toUtc().toIso8601String())
        .order('created_at', ascending: false);

    return (response as List)
        .map((row) => LogEntry.fromJson(row as Map<String, dynamic>))
        .toList();
  }

  // ── FETCH BY DATE RANGE (for trends) ────────────────────────────────────

  /// Fetch logs within a date range. Use for 7-day/30-day trends.
  Future<List<LogEntry>> fetchLogsByDateRange({
    required DateTime from,
    required DateTime to,
    String babyId = 'default',
    LogType? type,
  }) async {
    var query = _db
        .from(_table)
        .select()
        .eq('baby_id', babyId)
        .gte('created_at', from.toUtc().toIso8601String())
        .lte('created_at', to.toUtc().toIso8601String());

    if (type != null) {
      query = query.eq('type', type == LogType.diaper
          ? 'diaper'
          : type == LogType.feeding
              ? 'feeding'
              : 'symptom');
    }

    final response = await query.order('created_at', ascending: false);

    return (response as List)
        .map((row) => LogEntry.fromJson(row as Map<String, dynamic>))
        .toList();
  }

  // ── DELETE ──────────────────────────────────────────────────────────────

  /// Delete a log entry by ID.
  Future<void> deleteLog(String id) async {
    await _db.from(_table).delete().eq('id', id);
  }
}
